# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: build_binary
        steps:
          - task: NodeTool@0
            displayName: 'Install Node 16.x'
            inputs:
              versionSpec: '16.x'

          - task: CmdLine@2
            displayName: 'Build Binary'
            inputs:
              script: |
                npm install
                npm run build